version: "2"
services:
    django:
        build: ./django/
        expose:
         - "8000"
         - "8005"
        ports:
         - "127.0.0.1:8000:8000"
        depends_on:
         - db
    db:
        image: postgres
        environment:
         - POSTGRES_PASSWORD=bn@967
         - POSTGRES_USER=both_app
        ports:
         - "5432:5432"

